spring.application.name=petvida

logging.level.web=trace
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:h2:mem:petvidadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true